---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rustfs-secret
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef:
        key: rustfs
        property: username
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef:
        key: rustfs
        property: password
    - secretKey: RUSTFS_IDENTITY_OPENID_CLIENT_SECRET
      remoteRef:
        key: rustfs
        property: oidc-client-secret
