# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:AlsMMQKp/oHMVUpBwPaAHUv+yJ6uodn3NEgxXZMk8ot4RdtCQUEYVK56amAvifPeGcozv+hwYWCXyznJQLz3xeUAMLz7/mQSfZxBtfimB4kQMjcYxw6eUt18EWYPymxrtHIJ2Quc3hgQNTZXsQdz1p8f3cpOyrteS/UMjx31PgAMx7PeJzUMd78KoY+QXqxrL61b04ExNtNuDHl5PIb6JgD2u9oHTAPeRW2JkK4P4ghdqHpkrQ==,iv:1lKpk0/5yDSM4g17SfJiQj6VVCfsWsSd4OBdMiZD3gc=,tag:+3KJ1SndOy5MiMYObH3Ipw==,type:str]
sops:
  age:
    - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RHQ5VzdMb1BTcnF1cFBS
        c3VoYzBaZlMvSWVRKzB5OTUwZGJPMElrK1QwCmEvbGNaMEVtY0lRVDVMY21OcjlN
        TW1palQvNUpTaGIydmFaaVJkNXV0ZUkKLS0tIDB3cElDd0VTMTdvUVBZbUxuNUJY
        Qk4zNVNNbWRDSGtXQWpHeFpTaHhnM0UKe9j+u4USWoZs4HcaS6zTIUGBjp1/9ZcZ
        KVlU5vcf2W0I+L+lBDor3+13L8m41ZvsFeCtBIYrPIeiHyQ0MWVn3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T12:47:30Z"
  mac: ENC[AES256_GCM,data:jJ+mFB2Up67h9KHhbSJOXsUzUCkGEYD/S+MphU/vtaNVg9QsYQUT7Ic5YEtoFX8YMNzEh6XCPVwOEEGsIMfBnsn7I3WgqNewW9YjTFSg7L+k7r2DhtG2Qtk24LjYtMRMEJpvxMaTuPFxM+DZprAGWc4RyS5qRl9VAPlAFHMaSfc=,iv:iMhIEc6Ta7dq0t5a5fH6GsshQ/sxqxFc0e2AB9OtQ9o=,tag:rESrcUGrtAKqLCuCibdRyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
