---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops
  - ../../components/kopiur/secret

resources:
  - ./media-nfs.yaml
  - ./namespace.yaml
  - ./maintainerr/ks.yaml
  - ./seerr/ks.yaml
  - ./tautulli/ks.yaml
