---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/sops
  - ../../components/kopiur/secret

resources:
  - ./media-nfs.yaml
  - ./namespace.yaml
  - ./agregarr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./kometa/ks.yaml
  - ./maintainerr/ks.yaml
  - ./plex-auto-languages/ks.yaml
  - ./seerr/ks.yaml
  - ./tautulli/ks.yaml
