---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Merge
    creationPolicy: Owner
    name: minio-secret
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: minio
        property: username
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: minio
        property: password
