# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:eTuhOtJgvWUYcrw+94Ay+6qD6z/HHkb9s7EEz3jORu7n5jPpPQr/3Q==,iv:C2lQU4ZltykKagd5N06/vuV9BcUe7SzOdyauDEBmi3U=,tag:HtlQRTFhnX2fNdA99vcMBQ==,type:str]
sops:
  age:
    - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY0VibldvcWVjSEwvWDlD
        SVUxV25QOEJNTHpPd2NOazUvMC9Vd1pvSXpVCnU5ZTZjVWJWa3M5NVZPZ3F6dW5Z
        V1crU1dEZUx5UEZXMlJObW9uSW12RmMKLS0tIFBseG8vdDNjWWxUNUVCeGpUc1dB
        eDdFdzZ3b1JKdmtlL1QxUGU4RnJkdmsKF1vPYpD60iQkVhakPYH9a7hJRI0LZ+uG
        GGEj111QhulGx9/gpNJKogZGVL39NIHK++pYWpmDlMNXJxdDpasvCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T12:47:30Z"
  mac: ENC[AES256_GCM,data:skM/e3C+MTrL4B2wl4iddoO4X2G4vMutev89T7FxkJbGMcEws6ZAKZDbiWL4a7PC0WbVJS7LDLTtlxETzqzG7Z3aZFDA385R1Hj6Aw033ioBDhK5/1bMVuh4oBFx5AhfLB6mzcPnpbR/aZ+aaVhBbPbFuFkK0rtIk90wXJHYdAI=,iv:iiDjuny8xPZ6uuGyNe7F3GsKD6jB23FMH7vxLYYNHbM=,tag:jHi0c7Dw6/loMGOUHGETwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
