---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: datadog-credentials
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: &key b5fa3752-8762-41ae-8920-7f0562539bf5
        property: api-key
    - secretKey: app-key
      remoteRef:
        key: *key
        property: app-key
