---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-relay
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: smtp-relay-secret
    template:
      data:
        SMTP_RELAY_SERVER: "{{ .server | trim }}"
        SMTP_RELAY_USERNAME: "{{ .username | trim }}"
        SMTP_RELAY_PASSWORD: "{{ .password | trim }}"
        SMTP_RELAY_HOSTNAME: "{{ .hostname | trim }}"
        maddy.conf: |
          $(hostname) = {{ .hostname | trim }}
          $(server) = {{ .server | trim }}
          $(username) = {{ .username | trim }}
          $(password) = {{ .password | trim }}

          openmetrics tcp://0.0.0.0:9749 {
          }

          target.smtp remote_relay {
              hostname $(hostname)
              targets tcp://$(server):587
              starttls yes
              auth plain $(username) $(password)
          }

          smtp tcp://0.0.0.0:2525 {
              hostname $(hostname)
              limits {
                  all rate 20 1s
                  all concurrency 10
              }
              tls off
              default_source {
                  deliver_to &remote_relay
              }
          }
  data:
    - secretKey: server
      remoteRef:
        key: smtp-relay
        property: server
    - secretKey: username
      remoteRef:
        key: smtp-relay
        property: username
    - secretKey: password
      remoteRef:
        key: smtp-relay
        property: password
    - secretKey: hostname
      remoteRef:
        key: smtp-relay
        property: hostname
