apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FnQHHhhw3o7Un+89PS3oVekpmrY2eOb5UF0ck8Zi/r6fUwrY,iv:wfeurst+qT0BJmZS90KHdZt2gGwRcBtuVYVaAxVKMAA=,tag:dcSigryIw6uFpW7dhJe7gQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:pS29C6FoEIUFyd27lZhMPZQNFMhiTvd0g83OHXI9RzHZCcXqPkGaymT4OmCMOFCfM8vt9KuyDBssAoNMJhVCOL0199HUAIDJQck8JiulB6RGYvyv65e+UrGswOzMHRv7QN4IIb1QjN4UTMJXSxEr/yLS+A6Vd80uyzAIAZuJPGgY+7IqsAU0tcB/EIsANF4W8PErVhvdoboaakvFBuVrzo1K381fPD0GMBwPPlDCTQ==,iv:2qGF09DnGA9WK/pbI72fEsRtGiDiARtYnFcXCBT6JZY=,tag:pRtfnRCBJkqbiz6f1g7txQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb3IxVXZiemZ5dktISU5l
            czBsb2R5djRZZi84UzV3bEVsZ1Jwa3g5R240Ck95ZEMvSUgwMFdkQXN6ZkNhQlRK
            aVBKeWY3dm5YdFU3bWMyeUFtanFQbFUKLS0tIE1YS2ZnQ2hUb05rcEN3MDdhNWRv
            cXJBQW8xdERLVlhQNThtQzl3UDFxajAKhcfh2+K+fjHSqyGwMGbYjvFayTmHSSH1
            IyBkJSOovFmNu27ug0kUv+G90pLRl7RL0rN1wTJK8ZfKh8JRAzxN+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T22:41:25Z"
    mac: ENC[AES256_GCM,data:lLXTbNUrxwxuAX3fSQ9B4al3yW7uO9F1zaz0XdKoBxVPAIe/Xyp+Hb9kiakeStlVS0xNn3+AkiZ9uWDGuQvd46QG+aXnPJ9SkajBHq4bsw0iGU82o3+44AA2a8+k187wKiutXL9mHYYrsw5WVP1RJF91CpGFasWQmu9wOHZgFpc=,iv:iP0uf/PBFnJLfAML9m1TdJMtdf7NT9gEjH0dN4Fz4Os=,tag:c/Jwg/wFX2LSE3ZqvDjQNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
