apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:owrkjqdENZykdi5nKR3O/QmFXGL3FcsHCv4sXZA1xEP/kar3,iv:1CfLJ5SfUYZ5yNHhNnbXK4Q4bep2ifknwzvBk7IBEEE=,tag:nPjSwM8R38O7OHxk2bNcnA==,type:str]
    credentials.json: ENC[AES256_GCM,data:HzdPbrWS7hDZI8xTPPOnmZrHmPrOg5dn5SaBFNr9E9tbb2FLpTBEnbNV7GvSuB/Y/im5K831TCdJqtD/Nn3O6BStRUT+OfPQXWrZAPBojOfC52PQFrku0qp2nNdLEu4kgc1BtVcyNhVGhfdyiqN1zAlt+Rtfi2oY0AQJTdAs+Vv/PqM8dKZSGn+KzkRf0UYOlmv1Oq83PDLdVR7SMzzUjBeYGvSXMM7U614NpMAWJA==,iv:RgIn0q5G2MLxxKsdnrtq89aZl/GsWEfQBuYktFMl9mU=,tag:yRFgyffXgz7F+D0c/dJ3RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURFVEVTY4d2lPZW5kOTI5
            czNTM0FBZzRFSkJ2WXJNaTNBSmo0OWo1bms0Ckp0VVpHbVF2cTVCb0tFcTk3VVE4
            ZG0zVlJWYitQL1hUaER1Q3hTVnFHaU0KLS0tIElOYmNjVE85NlpndDcyMC9HYTd0
            UnczcHVRSlNKYVZnRS9EWDh4OEZnQzgKr1MFa+xvq7RiPASf/qm9tfx9Fm+yUwwC
            vgmwN99IAofw+V7W5I4zTiO34CroVVvdqKXItVVMBAIc28CKlLyoiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T21:25:29Z"
    mac: ENC[AES256_GCM,data:V19KsjyDkxmoe1mLPWMIw2HZp0Xs95qLxNGr3h9PFRT15gh4Z29mv5HKB74jd8vAK/pHWbunIyXorLdX9YJQHSrtFT76/pIwOx3emU0A4Js0BgHdqP5UPyfq3Owa+oWK4mUq5D2AzRt1gNKPQfHyo/J3aTu0JQ4Kkk3ho/7wq78=,iv:mw9QzFIVwn6PaDWdmzbSKOKqXpI26wM7HBkqNCLmkm8=,tag:DNY71TYrOZaviMhW9GcEfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
