apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Mj2dX2eTaksjyyPeFlkwz37LacLPaHWiiIKHD2fef4RbZR2g,iv:fD8RcQue+G8gKRb2eMbY5TumuMSUhsMd7J17D+5wUNU=,tag:6+i6kNPCd+kYnMjkED/9Qg==,type:str]
    credentials.json: ENC[AES256_GCM,data:BED+LBYOjulsLPIlv1OVrhsgP0uv0cH9itElJZpLiH+UK5suSH6SZ+UqeQVvZ0mAisrEVOBCqmu9Z01sLqxhxK3Qvmy+dgYdXHi+Zjz1/FDab2huZmNY9MUaCPV++HMouPenj4DFO7E3uunMe02oc7HclqmCvfv7CJaDw/OEbzoA0MTZf9omESQYIx/FTyID2Pi7AFvWwvwWe9xbExNF9JajAXdpo4+tysvfvKrKtg==,iv:EuZcIigfRnXmTFCyj0y1ZeZBOXH3p0U2ufZFBA0o2v0=,tag:pUxPeyBEip3lf9InwfNsuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MVVCZFZzL3RMWmdVRmx6
            dWZkZlVVT0FWbGF4bmxPSHdVdGR2eGdlY1ZNCjdsTzh4YjFBUVdIMWNnWm5BNUlW
            VWFSWmxwZS92RFdaNnFFc1RQTmNZVGMKLS0tIFZYN2F6SE8vRGFiUDh1VDdEeG5X
            cVNCL29iaHBsZW8yOStRVWw4S3pCMXcKHte+UQ86dbqbbUi11kSgDqV3cQZWbxt2
            O76WpWOZGoaAXfLepmk1yCDr8mMkOvcanI3Xq5lAkbKMfAops78WzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-29T22:35:24Z"
    mac: ENC[AES256_GCM,data:+hmuOmuYF90nN5VvoP2YMBTRM0FKYzw7nB4J1fBTHfIw6wv2I7f7t8SAo1dUTosKwL8vGlrRFhq9D8Wsgf7uTxN5Hq4ITrAAdn0Pmsn6b2REFS8VHztG20V2YEa/LA7h3YwCx275hAKAd6YtHFJbYg7cns69mWXraYsSqHSo954=,iv:HkFpT8INS6Hte3PHz1hQAHIjsN00REGj7d5Q1sxp/yE=,tag:3Ek6MpLzJeTK0ZMAuX32Bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
