---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: '{{ index . "repository-template" }}/${APP}'
        RESTIC_PASSWORD: '{{ index . "restic-password" }}'
        AWS_ACCESS_KEY_ID: '{{ index . "access-key" }}'
        AWS_SECRET_ACCESS_KEY: '{{ index . "secret-key" }}'
  data:
    - secretKey: repository-template
      remoteRef:
        key: volsync-restic-rustfs
        property: repository-template
    - secretKey: restic-password
      remoteRef:
        key: volsync-restic-rustfs
        property: restic-password
    - secretKey: access-key
      remoteRef:
        key: rustfs
        property: username
    - secretKey: secret-key
      remoteRef:
        key: rustfs
        property: password
