---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-dst"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-volsync-secret"
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:=1Gi}"
    moverSecurityContext:
      runAsUser: ${APP_UID:=1000}
      runAsGroup: ${APP_GID:=1000}
      fsGroup: ${APP_GID:=1000}
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
