apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Yr3AJYEWZgTO,iv:NVp64D3ERxOXrJUtEOUI5tMqkieP1JaYqIOjd4G9vms=,tag:fFSwgv2yECNMnbe+ImTCeQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHVsaG83Yi9v
        VjdjaGJxT2FySEp3c1RYZTlFSk45bXgvOVpDa0FKM0Rrd0lCU2ZmbDJBRFdXc0xn
        UHEzVHpvU3ZKNExnVzdvNkdIcFJRcEg2R1k0UjE0OGc0dkhJL1A1bkQyMjZZcTFS
        eTBzSlVmMmZwdXU0WTBpazFVUmZlbjJPZ0x1QVcxTVlrQWF4N3p5MXRCdStxV2px
        M3o4WlNGMHlEaVVuaTNKcVBZQ1crc2xxSElLNjZZWEVKUTFSRWtUZlJDM2M5R2l6
        THlUVHQ4TXRHeDdrVGRwNENJeWtXa3dIeXk0RSsrQUlKdllOVFRHMVRUK3FoUEFX
        Q2hubkVvcy83ZSs2SS9uNEFmYzVYTDBMK3NsWU5JRUVuY2o3OHJVTi90c3VyWjZ3
        aTE5cERSMFQ0YmoydUNnTkNYRnB5eEowcVNJcmpGL2FYZ1R3SElBVm1GWkw5TUM1
        WEdvVFkzR1pzTWpudUhiUkM4c1RvUnp2NE52c3pEa05raURSQjJBYlBXS3ZRNHJl
        SHdBTnp0U1RXcVQzd0FzdWRtd29wVnVveGRBY1V0VUdSN1plcnlrb2pTQU83WTRC
        VVN4OFlHUGZseTNHcUJ6d3NUTzVnMW5nUS8rT1hQbFNUNmRicTk2Tkd6cnc0WXdp
        RWxSY01BaTJnVXpCdDhDaVNIL0kxZzlzV3JGM2V5K2N1UUJadmtlK1lvbWR3L0dC
        Wm53Z1A4NitJQ2NUb0hJWk5qZEFyVUZzcnQ5S0tQcGxWS3ptc0FmNXBsYkdMUG9I
        M1IwQmpSUjN1WjVrazJMMWV5UGdZQXZGaFJ2bjZrY0pKOTI5TXhJQW4zdjdpVmhu
        ekNFblFBWE90UDFMeUNWOHd1aE0vbG9kOEZwcFBwajgrUzRiTmduRjcyVmt0cWM0
        ZklMVUNNdytzdm1UdWNHU3hCRWI2aXd5WnBwQVluelRPRVNTSFloYkpITVQxNkN1
        U1lFSFByVjcyQjlLcm8zeWJHcmJqZUNDRGZtRHk2UVBUT0hiNENwOGVpeW5GaWJF
        azB5YU1EYy9OV2szWTE0cU9CTWpHRDJDN0lwbHlEVTQyQjg2djI0OEV1V3RmUFpU
        eEFrYTg2VzQzdVlNcnBObm9yQmVSMWFXYzdvZ1gwdkxrY1Z3VXpSVTY4NFpjWHFQ
        OExIQVZ0UHBoK3hVMGVaQnBaSGVoVmMvNFZTWmcwQmxOSmFXNnpPM09CWWYxbFVH
        Y3lPU0ZqalcxUjFqZ0hwSGZROXBZS1NrRVZvbE8rVTdLUXFnYnNXejd2TzR3RVh4
        TjN5UlJJazgxQlRPaTdqYVJDVUozYnpCc1lENDE0MEFzazVpRzR3Ti9aeEdKZ0Vp
        MG1HaVJiTTZLVDNvR1dwR2tBYjdIbkF2K1JxdWw2STBzNEhsVnFiQVRad2xXd3hj
        VzBCQ3dycU8wU3cyai9nYm5xdTVDS0J4R0FiRGxCN2FFTlZYM1ltN3NaOG4zcy9j
        eXd5N01TVnFmajB0b0FvTnpRcy9tWStZWnNJUmdENU5vOENJRDM1ckhNaFdCWmp5
        blBkclk3dHQzZEgyNmhQNVpZamMvVkxSWTZyeEZIQmJtK1lMaTVwTHhHZHUvM0VC
        OUVrMU5KcUZmNldMeCtQbVhLcEVLSnRiN29ZUG9PQWlHSFBZcTR0bks5RTdMSjFq
        b2RwMDhHVDBWRFdzOHJaeDg1UHV3S2x3cTduaVdzN3NwcEFBVHJHc09QcFJ5eHJu
        Ym94azQwRHJtOUFFaTFISkI2WU1ra0lxblVrK1hIRzhVcFBISm56RlhzOEt0L3Mr
        VGw1UU81c3JqeG8zNFA0SEY1b2JLWVB6ZWJlL1JnUHJtUXBsNUx0amtaRmpRRm9u
        RWRuS0wzL0ZSWFJ5a0tJSkp6UjN3V2lsSjFCa1h1UXFHWmJuWk1SSktYL0VCL0xZ
        cEZTYUZRbG5QZUlFV0QwNVhBQ2I0d0ZKTTJFUTlrSEhoMUwydFJ3cTJrOEVXZwpy
        Q3E0ZlNIV0FRTjZDbWw2MnJ1QTA4TloydWsyRGYyVlJFeHdzV3lSM29zCi0tLSBj
        Ylh1THpBMUlpTzByeDYxS2FGcHoxUFBZUjgzR1ZudXJiUzVSV2JIbXVzCm1yTDP8
        N2K38fn+7x+PjwhEbMqMkVTg08hQvwBbybVF/aO2mkVCLMOtpm4f8s6k5KIJUcA2
        IVGrvERWGzq9kOk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1m9mn92qe8guy5sxy55zxkd7p7fer43mm0esv83rae9gmlxyjejmttwl3xxdzv8nag45eharj0kw28pwz3rxtznwa65xxvum5d3jer4hmysavdzaaz6c9czah68z6s7pc882lw7qc8zud663h9yjjawxhg9eytdrutd0c0ya6ds5vkp0tkt3ad0ctyz95t8rhq798uajrynjaez9vgawsqc6nr6jkzmq5sz93rpa7x2t9yvfms8nyzkgz3spfxmzc4zl4r8zqaw5fapdjz2t0q0a7n2jdv2cddf26xy7tp0hjglzhnqy6d9et4pu5c5ptfwp6n30spfuafyfusnesxgjs0t408jq5a92ag6qr74wy95v68zd49fktgwgncsekr9cv9eaq4z4kzucqx9c40v333635pgdcepqe4zwv8v87avutmlc27vksrdyc2u223f0nje6qqg2xfs3nsecz3jswzukte958yqunc3zctr3z0dplz885jweqwcdfkh4cefznkaw2q2u0kvq52vm3z0m4fzdtcwunx0qu2kg7mna6ran8kv77wv3xwea0z53tlnp5xdrjcfgtzza0sdffqgcrxqtx7e26jccyz3kk57mr7zfrn7vc8rhq28ngcse593wsy72zlk6y4hf2t6cqkjf3qe5cvv6s635tdrd33avqhgcllz85l6j2ws68e229ym262t6gctrme3etexr5k7akk8asenwezuah2fdzajfgrjsnkn3mjtydqj5lwa4gxrwpa8tk0lp3srf3vqggwqc5nymkrmcvjsrtjg5q9jwx04vnpf4ke08hn06szcq89sc8exms7vs6uk543jsyxdq44qvwxekxthje9we8h6u8s63y4yvehqfdpunug6f6h7383wtuvettq5jfhyynmx84q7gdcuglmyp4d29t0qp5ggq5ey0jg99s6d4nwj44c463zayrhs78cw3lt92vscg3uv9u9stf4pwdj5gw8zp0qcpgtdj6kmfh0t73hv4th8xglzrs32esls8s8t3xckhxc2u5kjcgtn52dhjjc9gmf296tspgl9pcgx53glpgnelxku4m8jwdjg2kefk9kzp6jnqr2al5fgsat5ut9jyrkfsgw0dyeqanz6j0043c6af3kxczv779zj9yh92fm9qzjsevd46v3dvpw706uy0a0hzhungsu37mvxflwgvjfpkgfs9gzyvecqueegzsfxszu88f5unvrn6vqe3y5fu4e2vv8xllnpnlscj8ur3kwtc58v9xds35mjx9rpfeqk058tra2dxj2xtlyqegqpvgfha8p9n2ycma679cadd8d4prwaxjkkka5cw402yflena5e5enx35f8fekcdksyu39tr4m76ql8at8y892d7ht36qjypz0ccv2t0k435wrra8qxdy42sl08ju56frgl69h93kkcveaqtnac9t4l2vsdrqxq5tkyfh5sxffeqpqxk5hjf2jg9tagkysfgqlzeprgn9wvy45nf8xcfdcujpdqn887gvg5n93vgwglzmgqjtyvegryjyx0rcnwdxuwxz5wm3aa5uym8hsr0a08n5x6d3v4kx8srf0xdh9htfe2crk4w3wunectfvsc0mx96rs5dps2vnkengc2ut0urcccm7sunfjwf0742nhwsv3dt297y92vvnjys3vmpkahp9m8rxg3tljexc25tw834vyv596ld5r447y6t8xy7f82e9kxz85qwpqrx3vnrwpw3e54sl5fry5q4844khshl566ep0cdklmjju65r50a8z6x7mdy3gqusdrn97fg9yrcycp4dsxry60jas7lg2c4ttghhmf9dxffye73ngj33qv2zez38wymwj94gyvdjh94gnm3spjngkl4hjttvdfqvw85uqkvckkdr3675qyyqnkmhzvsur2m5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-27T03:23:01Z"
  mac: ENC[AES256_GCM,data:gqeoQcSB1bYZWpfbKVsoK1+M/DFkoXuIl/po1g8Emi4S5BOH/70keDUd6M+oWSlQvYg09ogn2hFm74Q0VOE9FcKyYouTrs+xUCkx2atVqhqGPFwscvRjE1++ovf0dJDeyfBH6EMWE0L42FEhCLBdPjmGrCKe6Udp13sr58vw2Vs=,iv:4phwU0xknvbFfNB1ts9ihoz55ownNAFOFc828gjgi7w=,tag:yYcvMQ+CEnYtSYw1vYb14A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
