# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:UZe6nhuuTxAhCzaHmCkN9IyUOavZIBkLNvMSGmhw7Rc=,iv:4dZ1j34SQu8D7ikxi27iNhTGhYTbmTnZaJsTjb882t4=,tag:lnvjQhIpBp2HjxYjbDK3OA==,type:str]
sops:
  age:
    - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURUphMjcwQiszTkZFREFL
        ZzYvVkJjU0ZlZVNIQWpOc1h1cUYrUkZRRGlVCkVsTDJvWU5tRXhtZkh6ZnJxUGY0
        QVJSMTl2bkc0VzlHMlhRaFM4MmkybmcKLS0tIG52L3Y5Zmo1elZHVUpHSERhNEdH
        ajZEWllmQXFLREhWUmQ4QzBUQ0J3SFUKHKGNqXn+1U3WMPeASEehlthloRHHSG3r
        D10BV4RBSa5CznxCG38isdsH7DkegiL5KUZQBapiAzXTg4TiKofQ7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T12:47:30Z"
  mac: ENC[AES256_GCM,data:KcDuarkeJ7M4HluGB55QLXMKNxHgWWHcdLSA7Ckh4/OC/BaJdOd3iWO9NNGt8xSnYatoPcEd0vBeVploapCUChbI38sWln9fIcJtth/X+QCNLaF0Am1JUAVrSWjvf2sLWkST1wOgm9TX7ABVQjIvo34F0wDEfhTxmXPQIyWhnTY=,iv:ceXwyASZ4YFq4spZLD/ZC6YkPOUY7BWC436TUbhvNQo=,tag:c/Et1xQ8EzpJr5W4HOofzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
