---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads

components:
  - ../../components/sops
  - ../../components/kopiur/secret

resources:
  - ./media-nfs.yaml
  - ./namespace.yaml
  - ./flaresolverr/ks.yaml
  - ./gateway-oidc/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
