---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dashboards.yaml
  - ./datasources.yaml
  - ./externalsecret.yaml
  - ./grafana.yaml
  - ./httproute.yaml
  - ./pocketid.yaml
configMapGenerator:
  - name: dashboard-wan
    files:
      - wan.json=./dashboards/wan.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
