---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  wipe-disks:
    desc: Wipe Rook disks on all nodes in the cluster
    summary: |
      IMPORTANT: ROOK_DISK must be set to the disk model used across all the nodes (e.g. CT1000P3SSD8)
    cmd: bash {{.SCRIPTS_DIR}}/wipe-rook-disks.sh
    env:
      ROOK_DISK: "{{.ROOK_DISK}}"
    requires:
      vars: [ROOK_DISK]
    preconditions:
      - test -f {{.SCRIPTS_DIR}}/wipe-rook-disks.sh
