apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:B56d3ht5o2bSD44Xt1qMSWF9Kl1TCdq6zjPw5xYQreQGNckycp3CMg==,iv:gmjQykO/KB8feHtKQOYBkL2PvjybEPe1HiDKAvT3BLc=,tag:lujwnSC8e9wpVjWtrITCww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVWV6dmpJR0ZjSGlhVU05
            VWVKd3puOFFvWmFGblVDZ3UwV1FPd1ZUOFVvClhkcjF2TENqbjZlaEdLQWdrOUl5
            dVB1SHVnYXVudUpSLzdjaVF2ZWlNWHMKLS0tIDFsSTlLRm1FT052TUhYMnozQm5J
            eGNGVUlCNUJOU09YSXk3VG12czRPM3cK8pC4fz9J5IZtqWYetDOGAsEBtPH8MDwf
            nvdobcrYeZEC2S4HHiaTt6QKb4D6xVV79CMKbB060rfsXRn0FPYCyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T22:41:11Z"
    mac: ENC[AES256_GCM,data:phGrZ7XQlbDbgrnCPuk5wpVztHf5NE2et9v+7OaQYcYFrUENvoGCIsZwS8tjhK9IV3MQ/YLvOhbPDKJgUDt/A4UYoeuN57rnCZy+1jlNjWAWksuOKW+IrYC+6OxJN2ZzxB3YM0Am0cK1fLfTiZF0kIme8yWzuu31M4y0V+VCES8=,iv:OhxR+wK9/3lueMy48usjpIL25RFCnzAI7XgynBQS7m0=,tag:z0JccbdtX/Z58MbKcnkTVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
