apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:r4OvkIlp/POIBYkbrbK9KMjnzZtBP1xw3UKs+fPJExCuEOpYOxkujg==,iv:IXziG+noUA1ozmQSZ3P61O46i7XltrDPzGDkNLZZ4OA=,tag:a6rSX10b6sJ51ojT85lmKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWklSNUVLRWRDOGNrVmJz
            QU85emtQalJnWHNYZnI1T2FhS09XVWtDcWxvCjlFZ25icGM1aVpVV3BSZGdPOWUz
            T2lGVnYrbzJiL09yd0YvQWFYS1k2NDgKLS0tIDdBS1ZKVmpPUTFyTm5ndGMrOEk5
            bzVGZDJaeGRHU01yaTEvSSt2Qk9Ed0EKiSrerqOOJ73pElfqSLsO/PW4WaLCo4hR
            9A0XSl/YXsOw23/IdbbWYSf/eOxMxtnwxy+Ftk46ud9oRT5nzDRktQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-29T22:35:08Z"
    mac: ENC[AES256_GCM,data:9d6CeV1kYFLo/dTi0dAwHjdkzoDB5dfsg+OlrWay+qs1q83SPzhcEbfmWq3ss55fbIK6NoTwETFJGJRmia5dX5WEcWxKOsx8o5lmGNj3nf+sli/kW2bjHQIgiirKupUOw4/lNgcC608Y6sk/nMGrrJuAopVWyUAecOqELRpzHUc=,iv:Ynk2u4c3Zif6Jt6Bd+stCJ0hOYPTaj7t+LVb2+fOA+w=,tag:aRumSSf05VgvVCmImkYLjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
