apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DNNXgryhzxEXDmG+Gbg5VcyXtdGxmlOWaqSdEjHMBbsIWS1/GkYEqg==,iv:rVSC2IFxjabqTn6MuZFy5C70r7XZChPmk3LFUI9/4RM=,tag:bscw0IRo0EwMrzBoYKzdgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4K0lBNldCMnVxbVdoWktJ
            cUJpdjRwU0FyVUFhOTJxZGpTcFZIUmd0am1BCnl3OCthRlZyeXRpTUdxNUFlMUVL
            TXVsK0EyMzhZV2JyRGpNcHhJYXBRU3MKLS0tIDdsK0NpeSttY2tnb2h2dURtUWFk
            dXVqcmpLMlYvZVB2cDgvTkphSGVPZUUKJeAxrD3Xsr/6G/zcsepWYbDa/ZRkKYDB
            zsMKXP22Kk4IFFApbCs88DClz747hwiUG6+ql+cBnzFj78RydK4RgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T21:25:41Z"
    mac: ENC[AES256_GCM,data:k/e86shitc82Zi003EQiD6LNS7bfU+kQBDq+4apv+Ri+dvjlARprQe4ArofXeLcgpEicctsW8GdvN+hGAzp8d+B9k6w3v5m/T4ZERfU/DLEGfAiBRFZwJeLjukQ+HFHVGGJUySwnroqrg6D+s733zauYodelftJMyWrvk4YNlaM=,iv:vr2CtQRUImKg1DOJL6Z/QJXP79dU2ZhPhXEI/edRvQg=,tag:nnraQr8h0MrwmJOBw5ubhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
