---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: "external.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["c4003b2f-01ce-449c-a8b2-0aaa0c833339.cfargotunnel.com"]
