---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: music-assistant-skill
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Merge
    name: music-assistant-skill-secret
  data:
    - secretKey: APP_USERNAME
      remoteRef:
        key: music-assistant-skill
        property: username
    - secretKey: APP_PASSWORD
      remoteRef:
        key: music-assistant-skill
        property: password
