---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: weave-gitops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Merge
    creationPolicy: Owner
    name: cluster-user-auth # weave-gitops expects this name
  data:
    - secretKey: username
      remoteRef:
        key: "weave-gitops/username"
    - secretKey: password
      remoteRef:
        key: "weave-gitops/password"
