apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:h7CpC8bciglA,iv:OyG//qmft0/pJCXkUbkNp0RLE3Ssbme1uKS+aL+2fa8=,tag:txsJ3yg7oK7xHRrSROffow==,type:str]
sops:
  age:
    - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudTBZOVhHSGdrS2VJaFd0
        ajhlK1F6b3VIaVJneWlVRllNRHBvTjM5SG1FCnRaMUhCV0prdmZKUjkwVmJUQXV6
        dVNaaHBvNSsvTnkzbU9GSXZnQjRyMm8KLS0tIG1ZQkVkS3dFZGwyRFNqaFFLbjZ3
        MENsVWFxK2c3cU9VQk9leVZZeVF6UmcK5Lw9tscjfYzupm1csduquiwG/3X9JBeo
        mUw22k4BZ7CThO3mWuqANerTpDlRPyRY5vAFe6BhO7ypAkaJ98hdNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T12:47:30Z"
  mac: ENC[AES256_GCM,data:hpwA8a6l315PCy7i2PNmdwDLCZO2iH4GduxEZnI8fbxNJwF4DdQG55FS1TqrMb3xPjt5aAABLHftbxtu4bXCia2Cune7lq2psh7kSC/tbLLRE4H88z1YXAlu5u6TJMXQdKTebYDVqha9zD8W4EvBKWu4h3INaM/EFYHhQMmdDmU=,iv:3XvlHHvcYKAxGmoOaDsltkrsxqxpdCQmxZtJCArJpL4=,tag:lZ3RfggEqI9M4Pb4Ccssfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
