apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:rirBqD8kEbVSGVH41a7VV49f14bhdimlA5zxaTMjYxAKvc5v9Ku30ImGZhTG+76dvoY1NQVU/flcxOZcqrNReLjiL7C/Z4ebo/Y=,iv:kS27V38cgpEl/Egkk0ZmphRalsaay/Zz0BT/KF0e+Ms=,tag:4e3PtURRP/3Tv4Bwjjb7SQ==,type:str]
sops:
  age:
    - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUTNlajVIL0NXZnFHVC9J
        Yks1K1djVDg5Zm5ITDViT1A0eTV5ZlFKOFhJCldaTEZXZUF5eUhGc1RqVXREZkcw
        VjBwaEJkc2J6QXZnckpNMjV1c2R5alkKLS0tIGRCbUNzbTNsMHN6cTJJdzc3R1hm
        elZMTVFJaXQzUTVXZHdqTFN6OGFTVXMKVfKrCVjtKqAqQNmArhdgCj2Rxqa+KCwh
        zmCrO2n59dPXSzeFc+wKzCbobsmRXQIYi7ntnKY2y5TUVUqGhg7z8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T12:47:30Z"
  mac: ENC[AES256_GCM,data:gzRmN142EIPKUb7qPsT5hErWk14vUaxZB6gclDNKGVlILfviWSmxWfQtziaC2D9vqNbA3ko9ZTdXodBEsxCL5vtk8OGKcNuKm3v+D5ujJSNsJvfJ5NBKwiZEGM7juYx6IRj4DdhQdnWFQ/yQYpl2xg40ij8T5Pb5uLOQDpefhnk=,iv:CrE3tu3SJOKvqD8imyzf9+XVASLD2tqmkeb7eBWpTGY=,tag:6fr+md3Im3fEcVoeTQUbuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
