# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Iwvl14HU3oWjNGmOu5A2k344j19TL/7tMEP+hZYYfqD/TIuffQAv4w==,iv:v6Q3LEXQFOa3ma43WCDV0Shn/i73ZSf+hkFJBPXPGtU=,tag:SR4Gj3HHCNF1R+LYvrNnXw==,type:str]
sops:
  age:
    - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTVRKekxld0k3ZUduTUVs
        ei8wRWFXVStoS2dPT2thdlpUVHhHSU8xMWpzClNET1FGTWxYWDM2MDBncmNraDdQ
        VlRnK3JDQ1RlYW9sOTB2VjdaRG1TbnMKLS0tIC90NTQ0VVh1TWFyYXdldi9EUzJO
        Z3luQ1ZZL29oWnJLUWpxbnE0cmJaRGcK2Axe/qj3zsRi9l3XOcqhIm787iIaiG4P
        mKkfazOfc0zID45oA2TTnuOg/YK2J9q/HSdmeMFteH6jqtVVml/QKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T12:47:30Z"
  mac: ENC[AES256_GCM,data:hv8o6zKtmbea5D4r3BmsHSQ83EGaNMS7Aw/maCaTcv6VtOfm/8Pr3ixVdTzwDnwG0Dyx7r5cJMRT9+uQT3AiACvqgwLnTWqpHiPWNA5xeuS/BMWh8/9Spc9bCLXM8etlmwuDLiduL38JcKB7qCvyFqVMuWyhIhdJ2MtfRhZ4UoM=,iv:lAdDTv3XzjmjE9cKgPGy8GnXSdRx3GA/aneF6T7HIzY=,tag:qPvEtCFRaD5/LQrp9i9Odg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
