# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:QnQc/qrYTrMisUHFiFvVL7s4j8VLbp+Zu06EE+/mLvY2U1JA1skI8g==,iv:303v2qvBJLbwrFTZFELF3p65XjgHjffrJZAE3EO1JzM=,tag:SZvybOs46wnllcBBnRyouw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wk0lyvpes9j8ltgjjp3sagvvk9d4xrnqm6lun8zuazw0la4lf38qvxev8x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RzJRY0Y2ZUc4VmtmQjVE
        SWd2RURLUzZYQzZOaUZOSmZFTDJMOXZsQ0R3Ck9Ka3FTcktrSzJ6OVZvNmE4MXhX
        V05ub3hSL281bTRHNmxvcWR2TEdYaUkKLS0tIElwQVd2b0NnN0c4dGJzdFZjRU5r
        a29jR1BEM1luSlkyY0xlc1I5Ti84elEK2UORoEYaL2g0/7xjXIGSUboAzjMJbtJz
        w9D/r6y7SsKW2hn4EpibUfvIfpHwDnD9GJpSFWwCTPAtNbzdDIPo9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-08T10:29:47Z"
  mac: ENC[AES256_GCM,data:JetTJvnN0YqTbxMxsJ9oY+0FHLAKYBHung3hCm+1oB6JoPrTtrHGptB1JDd/ws5I7YNLxMObdKAL7MuRvpVoqHWGU+ummOYVCcjlg493Cg6+35WdJIleKzXChhp4KGcd9NCl/rLAOeYniirPeidAbszlHHa2404fBz24d/p8bcY=,iv:egXcrw5R6klo6akkxhvi9gEhrnUe+Eggi0aG2IYoYeM=,tag:I5T+UcTx/6wiTApdOqmXKw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
