---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: obsidian-couchdb-secret
  data:
    - secretKey: COUCHDB_USER
      remoteRef:
        key: obsidian-couchdb
        property: username
    - secretKey: COUCHDB_PASSWORD
      remoteRef:
        key: obsidian-couchdb
        property: password
