---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Merge
    creationPolicy: Owner
    name: obsidian-couchdb-secret
  data:
    - secretKey: couchdb-user
      remoteRef:
        key: "obsidian-couchdb/username"
    - secretKey: couchdb-password
      remoteRef:
        key: "obsidian-couchdb/password"
