apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FnKwl/JYJicw,iv:vq/njkqUmxCGMqx1KhBkC4pujw1+81vPk9ecaOh9hdU=,tag:xSfd8OVRyIZBMrH6du2RxQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ja4bW/QjiHQKtoxe5k34xxA=,iv:C2EKf5okFLZY9SJIlYzPSX6bf8A10EHtm0Izmw++BJY=,tag:kov11J+EtsqXmMbyLLoSRw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NlEz+UDeAg06uqPSJfuJmQ8Sjyw/6u74miG/40FNu8E4bMy2,iv:zT3qw0SabHqrU/lLwK85hrJowlOK/qRAqjW6BwyrV9M=,tag:zWJkxB9eHw21bCgwsP4gjA==,type:str]
    SECRET_NAS_HOST: ENC[AES256_GCM,data:oRx4sOHez0eBzkdFLpg=,iv:2mKlL/dkDBOrRIjZLpf8NOzzzODcNZHOecMzL4bVsW4=,tag:C7PATfre5YYsip3M/5ldEg==,type:str]
    SECRET_NAS_PATH: ENC[AES256_GCM,data:ubR+ZtsNa52diHdYe1jWAYg=,iv:6dlUaxajJQ+2bkaRpncG2QvnRp0Ba9UA0mQrzubPmFc=,tag:YpHNhq8ODwplW4eqCaShig==,type:str]
    SECRET_MEDIA_PATH: ENC[AES256_GCM,data:MKlZZXXUfyzp5UoFIw==,iv:XCYw05KyloVjqsXi17o1POGMGpnM9vUuD0Uz30vpzlU=,tag:FrP83k1M/618nXRfqe0nMw==,type:str]
    SECRET_PHOTOS_PATH: ENC[AES256_GCM,data:aCGZW3/vJZwA/XzdSgB0,iv:WNw3wfCiKZTwfTN7goks0MB1Q7BjZ0yUUxUH1gK9tWs=,tag:+Na6VcRbY1CvkuWbKH3UZg==,type:str]
    SECRET_TAILSCALE_PORT: ENC[AES256_GCM,data:1gcyJ6g=,iv:4WZnjs7udi90Q4ca25UAuWTA8rvw8CiOCGdXn+IdsTQ=,tag:NxDTEwMrrzy6RL6PaEDDHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eTlta3hsSlBqWTJPWEI1
            ZHlFZHhDMEF1RE5Dd3lpVUM1RGNXR3BCclVVCk12bWh4eWlDNUsvM3AxV2VzS0Ex
            UmV6OExzKzIxQVMxMFhuY0liQzQ5bG8KLS0tIFJXdWU0Sm00OVpPU1FhTmVpWFYy
            Rm5JMFZNZUU0MlZnRDZYVGZqWGc2TUEKMujgkZX12D5KNeSnDRV+4rOkiV1w+Jeg
            MUlrpvgW5LhH8Ce/60tIHcRkPdkwA24m+FPR6Z7Mznck9hUah9GshQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-28T20:04:08Z"
    mac: ENC[AES256_GCM,data:qwDrHqzrSj0sPy7BzOsEjPD3omxfWHb3q8q9v5DqdQpMJDbNGzQC9kj8F4SXsJY3rHii9Yz8TPU066xPD9wkVcMO1A7BNOtwAMmZn/7gtFZGlvpAplHlF5EjldAqZ7DOKaeSIz7Y74uyVVI84K5E+t60hO6ipWz+8GDWYhZRN8s=,iv:KegJorsSyeL4voKqBj/BaLPpVGgtSN5VopK5kescDZw=,tag:WwFVhux3ws7zFIU8PGZH5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
