apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:VMlZa0u0KgLW,iv:5UTgsH9bfCpbLFLMuvHzZqx5JnHPYzcsSqBMNqqwsN4=,tag:mMcAKkY9bXoPGnjeH4qSaw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZCf9mtAmJjO5nJELXar2VUo=,iv:kW2YO5QtdpAMaQdcdl/YC6W0cvqQyIwIuZCio5/JLK8=,tag:fBVNy5k8603Bqiojj77DnA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0cyK0MrwcfHBKR6T4VSBeYMBU+RLtnav1BfFUwC0ggT5knS+,iv:2ZhYaPJKyZGUoZU74WwYPlqclq2H6L2Q+0pvd5y5B3Q=,tag:hQdU1cFe8jev4vDEJRivnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcmJOZ1g5S3VranFaS3ZY
            NjdhNTM5ZnZ2V09QOHprZXZ2S0o5eWR1SzBVCnEwQ0ttZzR6a3paczVXcTlVV3Q1
            bHRFTFdGb2Q5UmozOXVsb1dCUFFmSFUKLS0tIE5pbk95OHFHR3RwejA1TkR3ZW04
            aERZL2xiYWphcG8yQU1IRHRPSHNpQzgKu3VAg/8jK+gXyD/7I3U77QVTZXbQ5wSR
            +d3HJY0FlvRq+P8gEEN3Lm5yvuTofsFB1ZvZWZwCg5iBt+tF5I1hkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-29T22:34:59Z"
    mac: ENC[AES256_GCM,data:haitzaXUV1bdiMMXTBXuMrqfZm85FM4gvPM2XjUHG82+8JX/zigRWoblgYVEEqutGHWfxNL1NM0Q34nbToUpGhwqKXz+bFIovzv4t+A1CMELTt33vqBP8OoiuAAjiKyvH7CuageFkwX8dfy1VQ2gXHZKmKqBvoydMCmkIVXuRF4=,iv:brvWG/Jf4pUrWHWILL68vJ9H7uAQ9uf4plmT+ltIMl0=,tag:H5qOPiMk+WGdEtjHwNs/3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
