apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:FnKwl/JYJicw,iv:vq/njkqUmxCGMqx1KhBkC4pujw1+81vPk9ecaOh9hdU=,tag:xSfd8OVRyIZBMrH6du2RxQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ja4bW/QjiHQKtoxe5k34xxA=,iv:C2EKf5okFLZY9SJIlYzPSX6bf8A10EHtm0Izmw++BJY=,tag:kov11J+EtsqXmMbyLLoSRw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NlEz+UDeAg06uqPSJfuJmQ8Sjyw/6u74miG/40FNu8E4bMy2,iv:zT3qw0SabHqrU/lLwK85hrJowlOK/qRAqjW6BwyrV9M=,tag:zWJkxB9eHw21bCgwsP4gjA==,type:str]
    SECRET_NAS_HOST: ENC[AES256_GCM,data:yKhnJ87RSeulU4c52Q==,iv:zViGlAwefMujHTn2MhNtb2HsFrLK9EZEwvJyMTGzncM=,tag:jlR2kMhnw/9RmiTJRqWiNg==,type:str]
    SECRET_NAS_PATH: ENC[AES256_GCM,data:ubR+ZtsNa52diHdYe1jWAYg=,iv:6dlUaxajJQ+2bkaRpncG2QvnRp0Ba9UA0mQrzubPmFc=,tag:YpHNhq8ODwplW4eqCaShig==,type:str]
    SECRET_MEDIA_PATH: ENC[AES256_GCM,data:MKlZZXXUfyzp5UoFIw==,iv:XCYw05KyloVjqsXi17o1POGMGpnM9vUuD0Uz30vpzlU=,tag:FrP83k1M/618nXRfqe0nMw==,type:str]
    SECRET_PHOTOS_PATH: ENC[AES256_GCM,data:aCGZW3/vJZwA/XzdSgB0,iv:WNw3wfCiKZTwfTN7goks0MB1Q7BjZ0yUUxUH1gK9tWs=,tag:+Na6VcRbY1CvkuWbKH3UZg==,type:str]
    SECRET_TAILSCALE_PORT: ENC[AES256_GCM,data:1gcyJ6g=,iv:4WZnjs7udi90Q4ca25UAuWTA8rvw8CiOCGdXn+IdsTQ=,tag:NxDTEwMrrzy6RL6PaEDDHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eTlta3hsSlBqWTJPWEI1
            ZHlFZHhDMEF1RE5Dd3lpVUM1RGNXR3BCclVVCk12bWh4eWlDNUsvM3AxV2VzS0Ex
            UmV6OExzKzIxQVMxMFhuY0liQzQ5bG8KLS0tIFJXdWU0Sm00OVpPU1FhTmVpWFYy
            Rm5JMFZNZUU0MlZnRDZYVGZqWGc2TUEKMujgkZX12D5KNeSnDRV+4rOkiV1w+Jeg
            MUlrpvgW5LhH8Ce/60tIHcRkPdkwA24m+FPR6Z7Mznck9hUah9GshQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T21:49:14Z"
    mac: ENC[AES256_GCM,data:arIRJEbRaeuvIG5rtRxPIDxqAP2keOvM7YJqO7zTy1Cd+sRYLd9omvXkND/BG6mVKFhiq0EDVMQoAl9K9jSTMZlQF9Uhnk+4LyfhPwOObrgBmKRAcE3dXcCVU1NqUGzs9LghvV/yvUXpB1KOCmgAZm5f4heS9cPRYVrdwuvPi9w=,iv:fDE9voN1nHXrGW/TrLG8qizmnZMqEfPsG9U97VeXJX8=,tag:vtuLNiP2YDSM6Fv1oJOl2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
