---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  storageClassName: media
  capacity:
    storage: 1Mi # doesn't matter
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.internal
    path: /volume1/data
  mountOptions:
    - nfsvers=4.1
    - nconnect=12
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: media
  resources:
    requests:
      storage: 1Mi # doesn't matter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
