---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obsidian-couchdb
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/kopiur/restore
  dependsOn:
    - name: kopiur-repository
      namespace: kopiur-system
    - name: onepassword-store
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/database/obsidian-couchdb/app
  postBuild:
    substitute:
      APP: obsidian-couchdb
      KOPIUR_CLAIM: obsidian-couchdb-data
      KOPIUR_CAPACITY: 2Gi
      KOPIUR_PUID: "5984"
      KOPIUR_PGID: "0"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: false
