apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:OouhJTUbbP5gZirym75658P6UtAm2wclg0iHMTjU85A=,iv:5y6RUfzKGagPYKVR5fvFI4tZpJd8keGmm6Y1n9AXNhc=,tag:4SZlOqpIRGOusH3Exz87HQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bzB6Y1NLYVFwTVNBUm00
            OVZ3VnFLYTlmY2xjcEVCTzkrY3ErTDQ2N0RFClRlSDZCSWhVRWgxMjVZb1hjcVc3
            YjVqV3JEZ2FSTE0weUFlYXA5bVdCRk0KLS0tIEVLdUlsMmsybktsc0JZYnViT0R2
            d1BrVEt6OHRoTU92b0JTcFdxZkRJQkEKKOln26hxYInOmMd7n5zOyqezjkgiD3O0
            nntWafRztaWqEAcdvDFYzgQ7O7xM6vCZ/U9qNYlVFspLu6hJUxGykw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T21:25:48Z"
    mac: ENC[AES256_GCM,data:33l9xMRcFUVaVDqfaQ7OsNtm77Bk4ywLGEImMAbUW5+EyG4U646IV05SreAWt9xJKDw21BTWq5Zyd/0jivuvQkMddBK4w6RWf67zThKD1emeWdltjjVe1rV74WJbOFOL2ODFceTyto4N17fTiN8fMRxB0t2cGV39DHJ+lsQBAX8=,iv:oowXReaW5NO3KFgeESp/kcu12vYmYGe7gLVdsA5JyPw=,tag:0IUSAwvK5ethtn+K/nvubQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
