apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:8crUxXhpZwCWOsdLaupbwe+JLEGaDXCcNUKhqR6Ljno=,iv:txmjNIPhuRVlatGHPcQ14GWan1hBn9a3DOQKtg1SpUc=,tag:gMu/QtBmWG3YqUqsRFEEfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCa1lMcCtvaVhHZHoxYlN2
            bEI3cHNONTFqTFYxVE4vZVduZkxjZ1B0ZUZVCkRmN1kyWVRDNFMxUUNib0QrZVEr
            TU5ZN1NKM2p6ZlQvSWRTRnhxOHBzV0UKLS0tIE8wbi9aVlNkUTd0T01WVThJNlRQ
            ZWhITWUwLzArbWhCSzE4MzhUMW5IT00KHJEv1i3x88m4yUTvaYQsM9HfLF1XcFDb
            M6IaC1zODzZiPtt3L20+vGYMAGXo9PuQW1bRGIdzS/cIGoTxLHNCUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T22:41:06Z"
    mac: ENC[AES256_GCM,data:oSm/f8aIlH4DkkpwEKZ3m7sowmsRRc3ycCivJ66nhAVjn37yOiiB8zfccFG+UkotvmweDiXt+03Mk7AU9hXX42TqmE2UduBi10l0YvqI4IX0o7y2g2uCD4wYKhteUAIgjAvA3v61vAcli395186x8U+CAoe2LQrFS51183X//9o=,iv:xQFRuT93d5H5zwgE3E1QILjbOEHWHyoT9ohC5cxzgws=,tag:6IZKwivtA4jOYXWx5K4ZlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
