apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:1PGGoml6i6vu3QfYqYLbDGGxaeuTQDh7M7DpKcDeGkc=,iv:BPWlGQJEbll4zDUD+ETnJ2hKiqHXNCFUlgaa58MZnk8=,tag:dgKen0wd0qXKsmcoM00fAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSWZJRWcxcnF4VnpIQ0dh
            UFVzUmZiUnFyWUl6YlZCTlMzUy96VW81YWxJCnBsUEZpRS9vQnpLU2dVdDBHUDFz
            VXZEMytlbGpJV2kwZFBwaTNoYmpNR0EKLS0tIDNDS0lVbTlrTyt0N20wUVJmQ1Ey
            NEYrcU9FR2lSMGwwSm5Obk9ONWhXMUUKVNzxuX2MPoXUioss2itV9aS3xhErQqvZ
            Lvj5Ed7K2a81B7niuMrWfXD4rqmD5hWV0s2sOtAG7wg3HytRw0teXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-29T22:35:04Z"
    mac: ENC[AES256_GCM,data:agQtK2qt5dqnYYw/3AgPdqiNQK1QGBm2UOr7ipOeE6X4zgpqGJwly8wxwCGRBQj2+XVqdWqYflCIFgl8uyssVnM1CON57nTRS2ksI9BfR469iEWl6vwR2NjvBfdllDO0QCUny0OGzQ9Y8DWijtDh/WGhXZsRNxxT9W6KDIX2Ips=,iv:5fyuBX0dhEA5nxOzQmpCen261bffhyLSYryo5KBim0o=,tag:YKoNf01n5xItLPUpmuC05w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
