---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc-unifi
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Merge
    name: go2rtc-unifi-secret
  data:
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: Unifi
        property: apiKey
    - secretKey: DOORBELL_RTSP_TOKEN
      remoteRef:
        key: Unifi
        property: doorbellRtspToken
    - secretKey: DOORBELL_CAMERA_ID
      remoteRef:
        key: Unifi
        property: doorbellCameraId
