apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:dwsaEtOBJN5u,iv:1aLz+AvPcbMHSDCeABSZPvxrhlT2Im8koC65+ZY0ObQ=,tag:6paxw5N5/njsrEOiTblN/w==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:0eMC1ZuW4IkwSDXMHA==,iv:2xZkvNIL5vzUYB/ejaKcpmNLXD01uHQMmU31MbFzglk=,tag:VXIMOhjGjXzA3xoEm4zESQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1wk0lyvpes9j8ltgjjp3sagvvk9d4xrnqm6lun8zuazw0la4lf38qvxev8x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb2VnMlNpMklCT3BncENi
        UnZqN0JVVVQrMk1jNkNHMHRZVkJVcDlIRkZnCjIzdlZETm5iMC9wdlRJbGVTQ1Yx
        UzFneTJQTHBaQVRMcXdCVHZtZU91c2cKLS0tIFVzQmxDY2d3ZHY5ZW4zRGs4S0N2
        b00wQnpOTXJDZ1g4TktoRkFXOXpkY0kKAAuBpCP3a9JU+hhf8dUpVgfM79KbKKhV
        Smu0DsrVEwi5mQXMyr+JUXUoaVv+q4oOS3wWE0bJCPtC9dmnGnvEcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-09T20:17:11Z"
  mac: ENC[AES256_GCM,data:FocbLmUq1Vq6Gc12b+4J1RmiggoA/RaJsqc6fQz2wMh0b0j0Jl+V/uAeVNHJ7zaIRXhgGodlMCBEwsIr9iKdCDaCdvfjcBZss0M2kcDXYlGs/8NDcpqvyHE8AU+zxw+wpgu5AP2W5bGBmVGAYnsA+zhOgsO/h23jWS52PDsYMyw=,iv:0RX/lZgqyas1EIbs+SOuhfpcH3FtNtn0qpq0+jnIF3E=,tag:z/xLR21sik4so0IKoQT7RA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
