apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:LTVHjJ3otWu9z1CKwNtqcF3HzmnV3+lj1xJ31y0uM+eAU+m1ekH3aQ==,iv:t7hJ5yzY7LPnQ/co9WldI36gbg1xWUTS/orXFHsq4EQ=,tag:e4hE9LkTfOQdqPHU0rxd6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdUd5ZWdPaG1CN3BTUkFy
            UTMwbTlsWVcwd051V1JJZUFVT2JIK2dYbUdBCjJIQk1JdFpPUDdPcG1XUXh6bC9K
            SjYwVHVVQUw0WjlZampydW44VGdhRXMKLS0tIE1nY3l0b2NqamdndE5HcnhYcGhJ
            bDA3VzdzaFlDVHZrRFg2NTQ1NDdvdDAKRNNcGyaSFe69ygSVcL/QZuF4K+u7wKgr
            ftSEwjgcFTkz/5MZ+T5CD3yDKGtPm6+Bo9t0fZBypm0OSklil/eNDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T21:25:33Z"
    mac: ENC[AES256_GCM,data:rX6O01swILYM1Vnfx8A7NHEnvMlFXFlpnOZPzzfQNQeulojsLfuPyl4UZFp6jio8OgVp9OCSV5EQXmEDjONmALyhucMEi1MWXqClqn8f9Owexk/TQjBhFxh3Bg/pCHUhUdqkimGxFosew/GXxrbfCg112dJ9mqI9SmRivHkjc7Q=,iv:3SalAfYdPB+ZQRa15CmaxcexhsdotGDOn48QIwaPp0s=,tag:G4kr7lxM3Fku+IXQ7VyEPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
