apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gCUIGQck1L9Yy2xxLWIQrmI/atTNxJddRgACUld7IGueCJjsQhO3cA==,iv:DxFkWUfWacGXJVN/BXRJBJFYyVUGKlqRoaoj/e6I9VY=,tag:pmKh7kLpf5zUYmbpyiQF2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K1F4UkZQZDZrMDN5VEor
            RVV2OC9vVlZWY2RZNnY2VS9GVWJ5ckZKM1FZCk0rSWhlOFpDSW1CQ0VpZTBPZU41
            NVlta29SNFFkWnZpTDNSVDNxdkJ3TnMKLS0tIGoxRmNMVVRYN01GUVhyKzMzeU9R
            K29VYkxlcGZ1UkhqOC83eXZSbUtkSWcK1cl1QLTQLmUfXq0kILBhTGqGNj+r8r6m
            RddTKh7DkX9FhJeqpu013oDSgzcgJ8424Jp2WibXz/azNU7XO0xauA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T22:41:17Z"
    mac: ENC[AES256_GCM,data:iZcH/ygYKo0QbArsfaTAzkPnc63/74UVIF9DkRasOWoOneF7RyJ9CP/jcdyB/kXSnjy4x/vd9Gg19+ARPIdwpx3FuGve1NtJRMBA70HxhgcUs1I1B722dRfQ+B/y+AAsiGm7u3s8W6yofC1PjWh+fA89nKisKvN2wgc0+KOsPBU=,iv:0R35lBKovc8q27IPT7ddmpAQEjRlISD7IFL19MfatPA=,tag:mGhZ5QjZgEW8L9ODF0ZuZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
