apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZXIv0ndDjnqPdiZn3CXQ/LVH2veR9WDUv7QzsjNSUTrLe8CAII5+KQ==,iv:YP4nN9SPQfqUjZWbFgdppGr9FaR8S7GI35ijMjYpR5Q=,tag:edkxPvCXlBLJLnLJWz+tPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ3piQndPcTdOd2pqaEE1
            L0JuSWZGMEk5VG5kdGJKYXV4RFNZTzZ0bDNvCmp5ako5c2IxSFRPUmZWd3pCRFpw
            RVdCWjF6NHliZmlWMElHWDVjU3AyNVUKLS0tIHUzcnlReGljTm9QVVMwdWlRR21Q
            V0kxUUV6aFQ3MVY5eVFxc1BlNWYzdkUKKR5c/BUYnKNS36cxNmgfvCBqg7gKyPoT
            n89D9DY9See/3GZtZ2radkm9sz43UbSjIRRiBGhgeA0yTLi2b3VFpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-29T22:35:13Z"
    mac: ENC[AES256_GCM,data:wAvjKaSN0wdhRaCujtuGa4dchEgDJBtefYb2RzTsAlllC+62i/dAHBJJt4Idf0B1bBf18Mc7revMwIdBSW0sl/Xg5cwa+yqAWIh8wFkVvXdEJ77oJajL2p89WTtfLnfu6yuOEAMtksMMnzXySYmRIh1SygH2s3lF9KwemCu8yGo=,iv:mpgXwsY6tOl2aOgivifdmPZriV9KHMl/Zc0lJdcDEvY=,tag:SnmkJ4pP7fyjUUKckevI7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
