# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-sdk-token
stringData:
  token: ENC[AES256_GCM,data:ZtFGVWabK2CjTMoxLR3+uc8Nb1VuFiMx9nL+nYdFjHDKsB+fo+Gtnie+uWfwg307sNeuJdJYw2xPMQ50DLLSwNmv+fNXZFbb0/umIA+D6LdQLD3bIr6wdHnMmikFfGyUb8Uke6GAUT3uaaj0rw+ESKqP0yE9vG2H77E/XtcVRxA6f0qD6gxLlWopwJXDh8cImEHHi7Yrr6r1m8+AWk31r0Ohj3+7c+1FmJJnAyO+k5prdaZHSifqTlzL7DDp4dG0B+rFpBPXl1v0nmq93wPChKrhGsBPb5GCaZEYoIu48wWM7+L2Pkztfm4u/Tnhl6QwASwLTvfc0s0EgK692/EHEnHfz/KJw7WTogPJ+fnRx4Dcm8iigLgUtOg806XTE9oNBcm2tR0a3f2ItmU3meHq4+ElLUEc4wD4AYuuwHbsSsngYEA/XC1OlUPnTM9mRGTI6mrxsj3byJnjloAei2Z2uobnOOAepPSt+fgZkayvl4bus1UgbT9Ww95+DxVId9Ta68lV/T6L/XLCTompqYaf7hRxcdylHjXj3H0lLqNqIGEnwNv2nQVzEfIUPAdJbgKNQRZRpOsF6twqBmih6BWnBrflXMZ1NMpRIRGbuSnQaY2ZSjGmMMYX9S9zI0MqA5Xd14gXDIY4obLsMm1RjgmNZuvk0E3oOHX+dYj6o+K7+cSRgbhWKC5vg4Og6vENtEo4nqhVuqUEN+2Nge9T3+OAOWt/kzQK6GtCaELYdoc9V7qTSenI9wBfwWiPnRFIrLWcvFNpzzW1CBUnVHVg4qFkQ8miZEtNWT3DpimhiSj7bohLvjjCxDeqCHBVCix6joHHGaPlzy8n+Kb/Ds37RWUy5/9ftkoIdwbrcYLOBwhnXii/r4WgXUgUcatzASXN4G4UnMZy6mGGh/9+iGewITInjXPqDRh1JBh1FsTURw3d3DHSBu7D61WwciDghvpNYOpecQdULlj+HwELLra/SMOB6kFbAKkVlmJY85kOvoXizPPor5BidbOS4d5UL4Yg5OLHBhNv7Mb4lSEXMdHfOxXBDiDFWsnuyyCHlsYxGd9Ac9GODP7g21CXYeb+V+MC2Sikk9tUROUS5nd1OEpQzNARBrCiIoggRy9VcP5wzTxnU1XObrEj,iv:SvwyVvqaPAa89K89P+KlRH8BaEowkBvpkxignAFzFtY=,tag:hvK76rjrJrwIvGZxV7uWig==,type:str]
sops:
  age:
    - recipient: age1uz7wnz65tnuzgjdup5djd4ujssd7sncqu36a3x4yjnlnd69fxdmqe7z76z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z0hNL0lJM0VOTTA5NEJk
        WUVSdGhVdnRPVFh6b2FCaGwxUytpVGF4bjBRCmdGS05vSC9uLzQ0R2dScStxYStz
        ZWpIaDdyMjNRdUhwRkRBZUxpRFFxZ3MKLS0tIGtiZXIrWFR5UjZORHNYc29kZWQx
        aFdrL1BOY2w0MjVyUXh1M3dCTk5WdHcKRxucRo8O/i5igAKlh+wp2Z2B0p/dFeE4
        87Qq5oIgpLSla18h2fHmehITHm1k9lOP19LuQvyOGxA+AloDNeAXYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-23T17:31:38Z"
  mac: ENC[AES256_GCM,data:C9XOMF0QSH3BXBS+MdPIRrBlAJBPsrOHkUN8xuGRlpAKcFTNEy+SghCSZ6CXDN6PbS/Q7eS+IZdonIk8X2ag7hydnrKvsROz3DBKJb1XUKrflgRANiQ2CyDt2CJDPjs3AasNjimBPu1TA2vakWIxb/bHdq16jVNdjDJsvZARFjI=,iv:lnjawsspP1Pq5mNR4nXjJjlFTwvbnGYBXnnqh9XcCYw=,tag:fafYXeYHJWxsH53Jz0CZAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
