---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
    localpv-provisioner:
      localpv:
        image:
          registry: quay.io/
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: /var/openebs/local
      helperPod:
        image:
          registry: quay.io/
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
    minio:
      enabled: false
