---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    deletionPolicy: Merge
    creationPolicy: Owner
    name: "${APP}-volsync-minio"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ index . "repository-template" }}/${APP}'
        RESTIC_PASSWORD: '{{ index . "restic-password" }}'
        AWS_ACCESS_KEY_ID: '{{ index . "access-key" }}'
        AWS_SECRET_ACCESS_KEY: '{{ index . "secret-key" }}'
  data:
    - secretKey: repository-template
      remoteRef:
        key: volsync-restic-minio
        property: repository-template
    - secretKey: restic-password
      remoteRef:
        key: volsync-restic-minio
        property: restic-password
    - secretKey: access-key
      remoteRef:
        key: minio
        property: username
    - secretKey: secret-key
      remoteRef:
        key: minio
        property: password
